version: "3.8"

services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: gptbot
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    bot:
        build: .
        environment:
            - BOT_TOKEN=${BOT_TOKEN}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - db

volumes:
    pgdata:
